name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: ifeedun/pytest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          pytest
